import { ScrollView, StyleSheet, Text, View } from 'react-native'
import React from 'react'

const BaoMatThongTin = () => {
  return (
    <ScrollView style={{ width: "100%" }}>
      <View style={{ justifyContent: "center", alignItems: "center" }}>
        <Text>CHÍNH SÁCH XỬ LÝ DỮ LIỆU CÁ NHÂN </Text>
        <Text style={{ marginTop: 20 }}>VÀ BẢO VỆ THÔNG TIN CÁ NHÂN NGƯỜI DÙNG</Text>
      </View>

      <View style={{ padding: 10 }}>
        <Text>1.Phạm vi thu thập{"\n"}polybarber thu thập các thông tin của Người dùng bao gồm dữ liệu cá nhân và các thông tin liên quan đến Người dùng khi sử dụng hệ thống. Cụ thể:</Text>
        <Text>- polybarber thu thập thông tin cá nhân từ Người dùng khi Người dùng điền vào biểu mẫu trên Website bao gồm nhưng không giới hạn: tên và mật khẩu đăng nhập, họ tên, email, số điện thoại, địa chỉ,,…{"\n"}- polybarber thu thập các ý kiến phản hồi từ Người sử dụng.{"\n"}- polybarber thu thập thông tin liên quan đến dịch vụ cung cấp bao gồm nhưng không giới hạn về hình ảnh, thông tin đặt lịch, sử dụng dịch vụ,… của Người sử dụng{"\n"}Người dùng có trách nhiệm đảm bảo những thông tin mà mình cung cấp là đầy đủ, chính xác, chân thực và luôn cập nhật. polybarber không chịu trách nhiệm giải quyết bất kỳ tranh chấp nào nếu thông tin Người dùng cung cấp không chính xác hoặc không được cập nhật hoặc giả mạo.</Text>
        <Text>2. Mục đích thu thập và xử lý dữ liệu{"\n"}Công ty thu thập thông tin từ Người dùng để:{"\n"}- Xác nhận đặt lịch sử dụng dịch vụ cho Khách hàng{"\n"}- Xác nhận thông tin giao nhận sản phẩm cung cấp cho Khách hàng{"\n"}- Vận hành và cải thiện chất lượng dịch vụ{"\n"}- Cá nhân hóa trải nghiệm của Người dùng: polybarber phân tích và đưa ra những dự đoán về nhu cầu của Người dùng và phân vùng để Người dùng được ưu tiên tiếp cận những vùng thông tin phù hợp nhất với nhu cầu đó.{"\n"}- Nâng cao chất lượng dịch vụ bằng việc gửi cách chăm sóc tóc, liên lạc giải quyết vấn đề khi khách hàng có trải nghiệm chưa tốt.{"\n"}- Giới thiệu tới Người dùng các thông tin mà polybarber cho rằng sẽ hữu ích, bao gồm nhưng không giới hạn các dịch vụ, chương trình ưu đãi và các gợi ý về tính năng.</Text>
        <Text>3.Những người hoặc tổ chức có thể tiếp cận với thông tin thu thập{"\n"}Khi thông tin được đăng tải lên polybarber.com, những đối tượng sau đây được quyền tiếp cận thông tin:{"\n"}+ Cán bộ, công nhân viên công ty có nhiệm vụ thu thập thông tin Khách hàng thuộc các bộ phận như Chăm Sóc Khách Hàng, Phân tích kinh doanh, Trải nghiệm Khách hàng, Công nghệ thông tin,… Khi cần thiết, chúng tôi có thể sử dụng những thông tin này để liên hệ trực tiếp với khách hàng dưới các hình thức như: xác nhận lịch đặt, giải đáp nhu cầu, thắc mắc,…{"\n"}Công ty có thể công bố các thông tin cá nhân thu thập từ khách hàng cho bên khác như đối tác để có thể chăm sóc khách hàng tốt nhất.{"\n"}+ Bên thứ ba được polybarber thuê, hợp tác, cộng tác để thực hiện một số chức năng cần thiết liên quan đến dịch vụ polybarber  cung cấp như: lưu trữ máy chủ, phân tích dữ liệu,nghiên cứu,  tìm kiếm giải pháp truyền thông, xử lý các vấn đề liên quan đến thanh toán, khiếu nại của Người dùng,...được tiếp cận thông tin trong phạm vi cần thiết để thực hiện các chức năng liên quan.{"\n"}Thông tin cá nhân của Người dùng sẽ không được chia sẻ với các doanh nghiệp hoặc tổ chức khác với bất cứ mục đích gì ngoài các mục đích nêu tại Phần "Mục đích thu thập và xử lý dữ liệu" nêu trên khi chưa được sự đồng ý của Người dùng. Tuy nhiên, Công ty có thể cung cấp các thông tin cho cơ quan chức năng khi được yêu cầu hoặc khi thông tin đó được xác định có ảnh hưởng, tác động tiêu cực cho Công ty trên cơ sở tuân thủ các quy định của Pháp luật.</Text>
        <Text>4.Hậu quả, thiệt hại không mong muốn có khả năng xảy ra{"\n"}Trong quá trình tiếp nhận, lưu trữ và xử lý dữ liệu của Người dùng, có thể phát sinh một số lỗi kỹ thuật hoặc sự đột nhập trái phép từ các đối tượng cố ý tấn công website. Khi đó, thông tin và dữ liệu của của Người dùng có thể bị dò rỉ, đánh cắp, thu thập trái phép từ nhóm đối tượng này.{"\n"}Trong phạm vi trách nhiệm của mình, polybarber đảm bảo duy trì các biện pháp kỹ thuật cần thiết để ngăn chặn  hành vi tấn công, đột nhập trái phép và nhanh chóng, kịp thời áp dụng biện pháp khắc phục khi nhận thấy  và bảo vệ dữ liệu của người dùng ở mức độ cao nhất.</Text>
        <Text>5.Cách thức xử lý dữ liệu{"\n"}polybarber xử lý dữ liệu sau khi tiếp nhận bằng cách thức sau:{"\n"}Dữ liệu được xử lý tự động thông qua các dạng phần mềm để đảm bảo sự bảo mật dữ liệu người dùng bao gồm:{"\n"}-  Phần mềm mã hóa: Giúp mã hóa dữ liệu để đảm bảo tính bảo mật khi lưu trữ hay truyền tải dữ liệu.{"\n"}-  Phần mềm quản lý danh sách kiểm soát truy cập: Hỗ trợ quản lý và kiểm soát quyền truy cập vào dữ liệu, đảm bảo chỉ người dùng được phép có quyền truy cập vào dữ liệu.{"\n"}-  Phần mềm xác thực: Hỗ trợ xác thực người dùng để đảm bảo chỉ có người dùng được phép truy cập vào dữ liệu.{"\n"}-  Phần mềm phát hiện xâm nhập: Giúp phát hiện các mối đe dọa đến tính bảo mật của dữ liệu và cảnh báo đơn vị sử dụng để có phương án đối phó.{"\n"}Bên cạnh hệ thống xử lý dữ liệu tự động, polybarber thành lập Bộ phận chuyên trách quản lý và xử lý dữ liệu dựa trên các tiêu chuẩn, quy trình và quy tắc quản lý của Công ty.</Text>
        <Text>6.Thời gian lưu trữ và xử lý thông tin, dữ liệu{"\n"}Mọi thông tin, dữ liệu được polybarber lưu trữ cho tới khi Người dùng yêu cầu xóa thông tin cá nhân của chính mình hoặc Chúng tôi cho rằng việc lưu trữ thông tin đó là không cần thiết.Thời gian bắt đầu và kết thúc xử lý dữ liệu: Dữ liệu được xử lý từ thời điểm polybarber tiếp cận được thông tin, dữ liệu do Người dùng đồng ý chia sẻ cho đến khi Người dùng có yêu cầu về việc hạn chế, xoá bỏ hoặc rút lại sự đồng ý về việc cho phép xử lý dữ liệu.</Text>
        <Text>7.Chỉnh sửa và xóa bỏ dữ liệu cá nhân.{"\n"}Người dùng có thể thay đổi hoặc xóa một phần hay toàn bộ thông tin mà mình đã nhập tại giao diện quản lý tài khoản cá nhân. polybarber có thể hỗ trợ xóa bỏ thông tin nếu Người dùng yêu cầu, tuy nhiên người yêu cầu sẽ phải chứng minh mình có quyền hợp pháp đối với các thông tin đó.</Text>
        <Text>8.Cam kết bảo mật dữ liệu cá nhân người dùng{"\n"}polybarber có các biện pháp thích hợp về kỹ thuật và an ninh để ngăn chặn việc truy cập, khai thác và sử dụng trái phép thông tin Người dùng. polybarber cũng thường xuyên phối hợp với các chuyên gia bảo mật nhằm cập nhật những thông tin mới nhất về an ninh mạng để đảm bảo sự an toàn về thông tin khi Người dùng truy cập, đăng ký mở tài khoản và/hoặc sử dụng các tính năng của polybarber.com. Khi thu thập dữ liệu, polybarber thực hiện lưu giữ và bảo mật thông tin Người dùng tại hệ thống máy chủ và các thông tin Người dùng này được bảo đảm an toàn bằng các hệ thống tường lửa (firewall), các biện pháp kiểm soát truy cập, mã hóa dữ liệu.{"\n"}polybarber không cung cấp thông tin Người dùng cho bất kỳ bên thứ ba nào trừ các trường hợp cung cấp thông tin nhằm thực hiện “Mục đích thu thập và xử lý dữ liệu” nêu trên, phải thực hiện theo yêu cầu của các cơ quan Nhà nước có thẩm quyền, hoặc theo quy định của pháp luật, hoặc khi việc cung cấp thông tin đó là cần thiết để polybarber cung cấp dịch vụ/tiện ích cho Người dùng (ví dụ: cung cấp các thông tin giao nhận cần thiết cho các đơn vị đối tác vận chuyển …).{"\n"}polybarber thành lập một bộ phận nhân sự chuyên trách (Bộ phận bảo vệ dữ liệu cá nhân) để quản lý và xử lý dữ liệu cá nhân của Người dùng, thường xuyên kiểm tra, giám sát hoạt động thu thập, lưu trữ thông tin, phát hiện và ngăn chặn kịp thời các sự cố phát sinh liên quan đến dữ liệu cá nhân của Người dùng.{"\n"}Ngoài các trường hợp nêu trên, polybarber sẽ có thông báo cụ thể cho Người dùng khi phải tiết lộ Thông Tin Người dùng cho một bên thứ ba nào khác. Trong trường hợp này, polybarber cam kết sẽ chỉ tiết lộ thông tin khi được sự đồng ý của Người dùng.</Text>
        <Text>9. Cơ chế tiếp nhận và giải quyết khiếu nại về bảo vệ thông tin Người dùng{"\n"}Khi phát hiện có sự vi phạm liên quan đến việc thông tin cá nhân trên Website bị sử dụng sai mục đích hoặc phạm vi nêu tại Đề án này, Người dùng có thể gửi thông tin khiếu nại đến polybarber  theo địa chỉ tiếp nhận sau:{"\n"}-   CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ polybarber{"\n"}-  Trụ sở chính: 82 Trần Đại Nghĩa, phường Đồng Tâm, quận Hai Bà Trưng, TP Hà Nội{"\n"}-  Điện thoại: 1900272703{"\n"}-  Email: cskh@polybarber.com</Text>
      </View>

    </ScrollView>
  )
}

export default BaoMatThongTin

const styles = StyleSheet.create({})